project:
  type: book

book:
  title: "Learning Diary"
  author: "Yinhao Ren"
  date: "1/19/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - wk1.qmd
    - wk2.qmd
    - wk3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



